# Generated by Django 6.0.4 on 2026-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('picture', 'Picture Gallery')], default='article', max_length=20),
        ),
    ]
