# Generated by Django 6.0.4 on 2026-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_article_video_url_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed link', null=True),
        ),
    ]
