# Generated by Django 6.0.4 on 2026-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video Transmission')], default='article', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255),
        ),
    ]
